version: '3'

services:
#================================================================================
# MYSQL
#================================================================================
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - dev-network
#================================================================================
# POSTGRES SERVER
#================================================================================
  #pg-docker:
    #image: postgres:14-alpine
    #container_name: dev-postgresql
    #environment:
      #POSTGRES_DB: mydatabase
      #POSTGRES_PASSWORD: 1234567
    #ports:
      #- 5433:5432
    #volumes:
      #- ./.data/postgresql/data:/var/lib/postgresql/data

#================================================================================
# PGADMIN
#================================================================================
  #pgadmin-docker:
    #image: dpage/pgadmin4
    #container_name: dev-pgadmin
    #environment:
      #PGADMIN_DEFAULT_EMAIL: me@example.com
      #PGADMIN_DEFAULT_PASSWORD: 1234567
    #ports:
      #- 5050:80
    #volumes:
      #- ./.data/pgadmin:/var/lib/pgadmin
    #depends_on:
      #- pg-docker
# ======================================================================================================================
# NETWORK
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge
